=== Hulkitos/Clase/Llenguatge de Marques/Tema 3 - Validacio XSD/Examen/AmengualSastreMiquelAngel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="llibreria" type="llibreriaType"/>

  <xs:simpleType name="codi">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3,4}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="llibreType">
    <xs:sequence>
      <xs:element name="titol">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="El Senyor del Anells"/>
            <xs:enumeration value="El Nom del Vent"/>
            <xs:enumeration value="Reina Roja"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="autor" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="JRR Tolkien"/>
            <xs:enumeration value="Patrick Rothfuss"/>
            <xs:enumeration value="Scott Farley"/>
            <xs:enumeration value="Juan Gomez-Jurado"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="editorial">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Minotauro"/>
            <xs:enumeration value="DEBOLSILLO"/>
            <xs:enumeration value="S.A. EDICIONES B"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="genere">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Fantasia"/>
            <xs:enumeration value="Novel·la Negra"/>
            <xs:enumeration value="Romàntica"/>
            <xs:enumeration value="Humor"/>
            <xs:enumeration value="Altres"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:choice minOccurs="0">
        <xs:element name="linkCompra" type="xs:string"/>
        <xs:element name="linkEbook" type="xs:string"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="codi" name="codi" use="required"/>
  </xs:complexType>
  <xs:complexType name="llibresType">
    <xs:sequence>
      <xs:element type="llibreType" name="llibre" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="comicType">
    <xs:sequence>
      <xs:element name="titol">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Batman: Año Uno"/>
            <xs:enumeration value="Watchmen"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="autor">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Frank Miller"/>
            <xs:enumeration value="Alan Moore"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="editorial"/>
      <xs:element name="dibuixant" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="David Mazzucchelli"/>
            <xs:enumeration value="Dave Gibbons"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="colorejador" minOccurs="0"/>
      <xs:element name="numero">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="7"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="descatalogatType" name="descatalogat" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute id="codi" name="codi" use="required"/>
  </xs:complexType>
  <xs:complexType name="descatalogatType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="data_des" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="comicsType">
    <xs:sequence>
      <xs:element type="comicType" name="comic" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="copiaType">
    <xs:sequence>
      <xs:element name="ISBN">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="ISBN_[0-9]{2,3}-[0-9]{2,3}-[A-Z]{2,3}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="num_edicio">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="5"/>
            <xs:enumeration value="9"/>
            <xs:enumeration value="1"/>
            <xs:enumeration value="50"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="data_impressio">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2015-09-02"/>
            <xs:enumeration value="2019-09-02"/>
            <xs:enumeration value="2006-07-02"/>
            <xs:enumeration value="2021-06-21"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="num_pag">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1515"/>
            <xs:enumeration value="420"/>
            <xs:enumeration value="415"/>
            <xs:enumeration value="260"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="llibre_comic" use="required" type="codi"/>
  </xs:complexType>
  <xs:complexType name="copiesType">
    <xs:sequence>
      <xs:element type="copiaType" name="copia" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="estantType">
    <xs:sequence>
      <xs:element name="numero_estant"/>
      <xs:element name="max_cap">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="150"/>
            <xs:enumeration value="120"/>
            <xs:enumeration value="350"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="copiesType" name="copies"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="estantsType">
    <xs:sequence>
      <xs:element type="estantType" name="estant" maxOccurs="10" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="seccioType">
    <xs:sequence>
      <xs:element name="codi">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="FTS"/>
            <xs:enumeration value="NN"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="nom">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Fantasia"/>
            <xs:enumeration value="Novel·la Negra"/>
            <xs:enumeration value="Romàntica"/>
            <xs:enumeration value="Humor"/>
            <xs:enumeration value="Altres"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="estantsType" name="estants"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="seccionsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="seccioType" name="seccio"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="llibreriaType">
    <xs:sequence>
      <xs:element type="llibresType" name="llibres"/>
      <xs:element type="comicsType" name="comics"/>
      <xs:element type="seccionsType" name="seccions" maxOccurs="10"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="nom" use="required" fixed="Món de llibres"/>
  </xs:complexType>
</xs:schema>

=== Hulkitos/Clase/Llenguatge de Marques/Tema 2 - Validacio DTD i XSD/XSD/Examen/MiquelAngelAmengualSastre.xml
<?xml version="1.0"?>
<!DOCTYPE llibreria [
        <!ELEMENT llibreria (llibres|comics|seccions)*>
        <!ATTLIST llibreria
                nom CDATA #REQUIRED
                xmlns:xs CDATA #REQUIRED
                xs:noNamespaceSchemaLocation CDATA #REQUIRED>
        <!ELEMENT llibres (llibre)*>
        <!ELEMENT llibre (titol|autor|editorial|genere|linkEbook|linkCompra)*>
        <!ATTLIST llibre
                codi CDATA #REQUIRED>
        <!ELEMENT titol (#PCDATA)>
        <!ELEMENT autor (#PCDATA)>
        <!ELEMENT editorial (#PCDATA)>
        <!ELEMENT genere (#PCDATA)>
        <!ELEMENT linkEbook (#PCDATA)>
        <!ELEMENT linkCompra (#PCDATA)>
        <!ELEMENT comics (comic)*>
        <!ELEMENT comic (titol|autor|editorial|dibuixant|colorejador|numero|descatalogat)*>
        <!ATTLIST comic
                codi CDATA #REQUIRED>
        <!ELEMENT dibuixant (#PCDATA)>
        <!ELEMENT colorejador (#PCDATA)>
        <!ELEMENT numero (#PCDATA)>
        <!ELEMENT descatalogat (#PCDATA)>
        <!ATTLIST descatalogat
                data_des CDATA #REQUIRED>
        <!ELEMENT seccions (seccio)*>
        <!ELEMENT seccio (codi|nom|estants)*>
        <!ELEMENT codi (#PCDATA)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT estants (estant)*>
        <!ELEMENT estant (numero_estant|max_cap|copies)*>
        <!ELEMENT numero_estant (#PCDATA)>
        <!ELEMENT max_cap (#PCDATA)>
        <!ELEMENT copies (copia)*>
        <!ELEMENT copia (ISBN|num_edicio|data_impressio|num_pag)*>
        <!ATTLIST copia
                llibre_comic CDATA #REQUIRED>
        <!ELEMENT ISBN (#PCDATA)>
        <!ELEMENT num_edicio (#PCDATA)>
        <!ELEMENT data_impressio (#PCDATA)>
        <!ELEMENT num_pag (#PCDATA)>
        ]>
<llibreria nom="Món de llibres"
           xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
           xs:noNamespaceSchemaLocation="AmengualSastreMiquelAngel.xsd">

    <llibres>
        <llibre codi="ESDA">
            <titol>El Senyor del Anells</titol>
            <autor>JRR Tolkien</autor>
            <editorial>Minotauro</editorial>
            <genere>Fantasia</genere>
            <linkEbook>https://www.casadellibro.com/ebook-aquitania-ebook/9788408237747/11844504</linkEbook>
        </llibre>
        <llibre codi="ENDV">
            <titol>El Nom del Vent</titol>
            <autor>Patrick Rothfuss</autor>
            <autor>Scott Farley</autor>
            <editorial>DEBOLSILLO</editorial>
            <genere>Fantasia</genere>
        </llibre>
        <llibre codi="RRO">
            <titol>Reina Roja</titol>
            <autor>Juan Gomez-Jurado</autor>
            <editorial>S.A. EDICIONES B</editorial>
            <genere>Novel·la Negra</genere>
            <linkCompra>https://www.casadellibro.com/ebook-aquitania-ebook/9788408237747/11844504</linkCompra>
        </llibre>
    </llibres>

    <comics>
        <comic codi="BAU">
            <titol>Batman: Año Uno</titol>
            <autor>Frank Miller</autor>
            <editorial>ECC</editorial>
            <dibuixant>David Mazzucchelli</dibuixant>
            <colorejador>Richmond Lewis</colorejador>
            <numero>1</numero>
        </comic>
        <comic codi="WAT">
            <titol>Watchmen</titol>
            <autor>Alan Moore</autor>
            <editorial>ECC</editorial>
            <dibuixant>Dave Gibbons</dibuixant>
            <numero>7</numero>
            <descatalogat data_des="2010-11-12"/>
        </comic>
    </comics>

    <seccions>
        <seccio>
            <codi>FTS</codi>
            <nom>Fantasia</nom>
            <estants>
                <estant>
                    <numero_estant>10</numero_estant>
                    <max_cap>150</max_cap>
                    <copies>
                        <copia llibre_comic="ESDA">
                            <ISBN>ISBN_987-92-JK</ISBN>
                            <num_edicio>5</num_edicio>
                            <data_impressio>2015-09-02</data_impressio>
                            <num_pag>1515</num_pag>
                        </copia>
                        <copia llibre_comic="ENDV">
                            <ISBN>ISBN_77-92-ABD</ISBN>
                            <num_edicio>9</num_edicio>
                            <data_impressio>2019-09-02</data_impressio>
                            <num_pag>420</num_pag>
                        </copia>
                    </copies>
                </estant>
                <estant>
                    <numero_estant>11</numero_estant>
                    <max_cap>120</max_cap>
                    <copies>
                        <copia llibre_comic="ENDV">
                            <ISBN>ISBN_69-928-YT</ISBN>
                            <num_edicio>1</num_edicio>
                            <data_impressio>2006-07-02</data_impressio>
                            <num_pag>415</num_pag>
                        </copia>
                    </copies>
                </estant>
            </estants>
        </seccio>

        <seccio>
            <codi>NN</codi>
            <nom>Novel·la Negra</nom>
            <estants>
                <estant>
                    <numero_estant>2</numero_estant>
                    <max_cap>350</max_cap>
                    <copies>
                        <copia llibre_comic="RRO">
                            <ISBN>ISBN_22-33-JGJ</ISBN>
                            <num_edicio>50</num_edicio>
                            <data_impressio>2021-06-21</data_impressio>
                            <num_pag>260</num_pag>
                        </copia>
                    </copies>
                </estant>
            </estants>
        </seccio>
    </seccions>
</llibreria>
