=== Hulkitos/Clase/Llenguatge de Marques/Tema 3 - Validacio XSD/Exercici no Entregable - Part 2/cuina_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ingredients">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ingredient" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="t_importancia">
        <xs:restriction base="xs:string">
            <xs:enumeration value="base"/>
            <xs:enumeration value="important"/>
            <xs:enumeration value="extra"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="t_codi">
        <xs:restriction base="xs:string">
            <xs:length value="3"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="calories_int">
        <xs:restriction base="xs:positiveInteger">
            <xs:maxInclusive value="500"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="ingredient">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="t_codi" name="codi"/>
                <xs:element type="xs:string" name="nom"/>
                <xs:element type="calories_int" name="calories"/>
                <xs:element type="t_importancia" minOccurs="0" name="importancia"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Hulkitos/Clase/Llenguatge de Marques/Tema 2 - Validacio DTD i XSD/XSD/Exercici no Entregable - Part 2/cuina_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ingredients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="cuina_2.xsd">
    <ingredient>
        <codi>org</codi>
        <nom>orenga</nom>
        <calories>500</calories>
        <importancia>important</importancia>
    </ingredient>
    <ingredient>
        <codi>frg</codi>
        <nom>formatge</nom>
        <calories>46</calories>
        <importancia>base</importancia>
    </ingredient>
    <ingredient>
        <codi>msa</codi>
        <nom>massa</nom>
        <calories>46</calories>
    </ingredient>
    <ingredient>
        <codi>gmb</codi>
        <nom>gambes</nom>
        <calories>46</calories>
        <importancia>extra</importancia>
    </ingredient>
</ingredients>
