=== Hulkitos/Clase/Llenguatge de Marques/Tema 2 - Validacio DTD i XSD/XSD/Ex/clinica-veterinaria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="clinica" type="clinicaType"/>

  <xs:element name="id">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z]{2}-[0-9]{2}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:complexType name="veterinari-1Type">
    <xs:sequence>
      <xs:element type="xs:string" name="nom"/>
      <xs:element ref="id"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="veterinari-2Type">
    <xs:sequence>
      <xs:element type="xs:string" name="nom"/>
      <xs:element ref="id"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="veterinarisType">
    <xs:sequence>
      <xs:element type="veterinari-1Type" name="veterinari-1"/>
      <xs:element type="veterinari-2Type" name="veterinari-2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="professionalsType">
    <xs:sequence>
      <xs:element type="veterinarisType" name="veterinaris"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="raça">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="pura"/>
        <xs:enumeration value="perillosa"/>
        <xs:enumeration value=""/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:complexType name="ca-1Type">
    <xs:sequence>
      <xs:element type="xs:string" name="nom"/>
      <xs:element type="xs:string" name="data-neixement"/>
      <xs:element ref="raça"/>
      <xs:element type="xs:string" name="castrats"/>
      <xs:element type="xs:string" name="assegurançca"/>
      <xs:element type="xs:string" name="professional-assignat"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ca-2Type">
    <xs:sequence>
      <xs:element type="xs:string" name="nom"/>
      <xs:element type="xs:string" name="data-neixement"/>
      <xs:element ref="raça"/>
      <xs:element type="xs:string" name="castrats"/>
      <xs:element type="xs:string" name="assegurançca"/>
      <xs:element type="xs:string" name="professional-assignat"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cansType">
    <xs:sequence>
      <xs:element type="ca-1Type" name="ca-1"/>
      <xs:element type="ca-2Type" name="ca-2"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="pelatge">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="curt"/>
        <xs:enumeration value="llarg"/>
        <xs:enumeration value="pelat"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:complexType name="moix-1Type">
    <xs:sequence>
      <xs:element type="xs:string" name="nom"/>
      <xs:element type="xs:string" name="data-neixement"/>
      <xs:element ref="raça"/>
      <xs:element type="xs:string" name="castrats"/>
      <xs:element type="xs:string" name="professional-assignat"/>
      <xs:element ref="pelatge"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="moix-2Type">
    <xs:sequence>
      <xs:element type="xs:string" name="nom"/>
      <xs:element type="xs:string" name="data-neixement"/>
      <xs:element ref="raça"/>
      <xs:element type="xs:string" name="castrats"/>
      <xs:element type="xs:string" name="professional-assignat"/>
      <xs:element ref="pelatge"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="moixType">
    <xs:sequence>
      <xs:element type="moix-1Type" name="moix-1"/>
      <xs:element type="moix-2Type" name="moix-2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mascotesType">
    <xs:sequence>
      <xs:element type="cansType" name="cans"/>
      <xs:element type="moixType" name="moix"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="dni">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{8}[a-zA-Z]{1}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:complexType name="client-1Type">
    <xs:sequence>
      <xs:element type="xs:string" name="nom"/>
      <xs:element type="xs:string" name="llinatges"/>
      <xs:element type="xs:string" name="data-neixement"/>
      <xs:element ref="dni"/>
      <xs:element type="mascotesType" name="mascotes"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fitxesType">
    <xs:sequence>
      <xs:element type="client-1Type" name="client-1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="clinicaType">
    <xs:sequence>
      <xs:element type="professionalsType" name="professionals"/>
      <xs:element type="fitxesType" name="fitxes"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="nom"/>
  </xs:complexType>
</xs:schema>

=== Hulkitos/Clase/Llenguatge de Marques/Tema 2 - Validacio DTD i XSD/XSD/Ex/clinica-veterinaria.xml
<clinica nom="Animal Kingdom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="clinica-veterinaria.xsd">

    <professionals>
        <veterinaris>
            <veterinari-1>
                <nom>Curtis Wilder</nom>
                <id>AO-67</id>
            </veterinari-1>
            <veterinari-2>
                <nom>Knox Remington</nom>
                <id>YU-52</id>
            </veterinari-2>
        </veterinaris>
    </professionals>

    <fitxes>
        <client-1>
            <nom>Joan</nom>
            <llinatges>Planas</llinatges>
            <data-neixement></data-neixement>
            <dni>42856854A</dni>
            <mascotes>
                <cans>
                    <ca-1>
                        <nom>Hunter</nom>
                        <data-neixement>7/12/2019</data-neixement>
                        <raça>perillosa</raça>
                        <castrats>No</castrats>
                        <assegurançca>17656</assegurançca>
                        <professional-assignat>veterinari-1</professional-assignat>
                    </ca-1>
                    <ca-2>
                        <nom>Liam</nom>
                        <data-neixement>9/10/2018</data-neixement>
                        <raça>pura</raça>
                        <castrats>Si</castrats>
                        <assegurançca></assegurançca>
                        <professional-assignat>veterinari-1</professional-assignat>
                    </ca-2>
                </cans>
                <moix>
                    <moix-1>
                        <nom>Garrett</nom>
                        <data-neixement>19/02/2010</data-neixement>
                        <raça>pura</raça>
                        <castrats>Si</castrats>
                        <professional-assignat>veterinari-2</professional-assignat>
                        <pelatge>curt</pelatge>
                    </moix-1>
                    <moix-2>
                        <nom>Blake</nom>
                        <data-neixement>10/8/2017</data-neixement>
                        <raça></raça>
                        <castrats>No</castrats>
                        <professional-assignat>veterinari-2</professional-assignat>
                        <pelatge>llarg</pelatge>
                    </moix-2>
                </moix>
            </mascotes>
        </client-1>
    </fitxes>

</clinica>
